version: 2.1
orbs:
  node: 'circleci/node@3.0.1'
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          name: Run linters
          command: yarn lint
      - run:
          name: Run tests
          command: yarn test
workflows:
  test:
    jobs:
      - test
